-- 1. Create a Warehouse
CREATE OR REPLACE WAREHOUSE FPA_WAREHOUSE
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- 2. Create our "Raw" Database 
CREATE OR REPLACE DATABASE RAW_DATA;
CREATE OR REPLACE SCHEMA RAW_DATA.STAGING;

-- 3. Create our Analytics Database 
CREATE OR REPLACE DATABASE ANALYTICS;
CREATE OR REPLACE SCHEMA ANALYTICS.FINANCE;
CREATE OR REPLACE SCHEMA ANALYTICS.OPERATIONS;

-- 4. Create our Raw Staging Tables
-- These are the empty tables that will hold the data when we upload it.
USE DATABASE RAW_DATA;
USE SCHEMA STAGING;

-- Table for raw accounting transactions 
CREATE OR REPLACE TABLE RAW_TRANSACTIONS (
    TRANSACTION_ID VARCHAR(50),
    TRANSACTION_DATE DATE,
    AMOUNT NUMBER(12, 2),
    DEPARTMENT VARCHAR(50),
    PRODUCT_LINE VARCHAR(50)
);

-- Table for the monthly budget
CREATE OR REPLACE TABLE RAW_BUDGET (
    BUDGET_MONTH DATE,
    DEPARTMENT VARCHAR(50),
    BUDGET_AMOUNT NUMBER(15, 2)
);

-- Table for daily operational metrics (Drivers)
CREATE OR REPLACE TABLE RAW_DRIVERS (
    METRIC_DATE DATE,
    LEADS_GENERATED INT,
    SALES_REPS_ACTIVE INT,
    WEBSITE_VISITORS INT
);